development:
    adapter: postgresql
    encoding: unicode
    database: techguru_development
    pool: 5
    username: jiweiweisg
    password:
    host: localhost

test:
    adapter: postgresql
    encoding: unicode
    database: techguru_test
    pool: 5
    username: jiweiweisg
    password:
      host: localhost
